/* C library headers must use the implementation-reserved namespace for guards,
 * type plumbing, and implementation extensions so they cannot collide with users.
 */
// NOLINTBEGIN(bugprone-reserved-identifier,cert-dcl37-c,cert-dcl51-cpp)

/* SPDX-FileCopyrightText: (C) 2026 Gavin John
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 * <wctype.h> -- https://pubs.opengroup.org/onlinepubs/9699919799/basedefs/wctype.h.html
 *
 * ntlibc is C/POSIX-locale-only (src/misc/locale.c never accepts any
 * other locale name), and wchar_t here is a 16-bit UTF-16 code unit
 * (WCHAR_MAX == 0xffff, see wchar.h), not the 32-bit-holds-one-codepoint
 * type POSIX text elsewhere implicitly assumes.  What follows from that,
 * documented once here rather than per function:
 *
 *  - Classification and case mapping ARE real Unicode, not ASCII-only.
 *    An earlier revision of this header took the opposite position --
 *    ASCII-only, deliberately mirroring ctype.h's is*() family so that
 *    iswalpha() could never disagree with isalpha() -- on the theory
 *    that the C locale does not require classifying anything outside
 *    the portable character set.  That position has been reopened: this
 *    tree's own encoding story is UTF-8-only end to end (src/internal/
 *    utf.c), and a C library that decodes UTF-8 correctly but then
 *    tells every caller that "é" is not a letter is a worse library,
 *    not a more consistent one.  isw*()/tow*() (src/ctype/isw*.c,
 *    src/ctype/tow*.c) now answer from real Unicode Character Database
 *    data -- General_Category, the Alphabetic/Uppercase/Lowercase/
 *    White_Space/Hex_Digit derived properties, and the simple case
 *    mapping fields -- generated by tools/gen-unicode-tables.py from a
 *    real, versioned Unicode release (see that script's own docstring
 *    for the exact version and the property backing each function) into
 *    src/internal/unicode_tables.c, looked up by src/internal/
 *    unicode_data.c.  Every table only needs entries for U+0000-U+FFFF,
 *    because that is the entire domain a single wchar_t can name here.
 *
 *    towupper()/towlower() use only *simple* (1:1, locale-blind) case
 *    mappings -- the POSIX-mandatory bar and no more.  Real case
 *    *folding* is explicitly out of scope: locale-sensitive special
 *    casing (Turkish dotless i/dotted I) needs locale data this tree's
 *    single C/POSIX locale has no slot for, and one-to-many mappings
 *    (German sharp s "ß" folding to "SS") cannot be represented by a
 *    function that returns one wint_t. A code point with no simple
 *    mapping (sharp s included) is returned unchanged, which is the
 *    correct, conforming answer for "simple" mapping, not a gap.
 *
 *    isalpha() et al. (ctype.h) deliberately do NOT follow suit and
 *    stay ASCII-only -- see that header's own comment for why: a raw
 *    byte in 0x80-0xff is never a complete decoded character under this
 *    tree's UTF-8 model (it is always a lead or continuation byte of a
 *    multi-byte sequence), so isalpha() answering false for it is
 *    already the UTF-8-correct answer, not an ASCII limitation this
 *    header needed to match. The two families no longer need to agree
 *    past 0x7f, and now genuinely do not: iswalpha(L'\xe9') (the
 *    decoded code point U+00E9, é) is true where isalpha(0xe9) (one raw
 *    UTF-8 lead byte, not a character) stays false. That is UTF-8
 *    correctness, not the inconsistency an earlier revision of this
 *    comment worried about.
 *
 *  - A lone surrogate half (0xd800-0xdfff) is not a valid character;
 *    iswalpha.html's DESCRIPTION restricts the domain to "a valid
 *    wide-character code, or ... WEOF" and says behaviour is undefined
 *    for anything else. ntlibc picks a defined answer anyway: every
 *    classification function returns 0 (false) and every conversion
 *    function returns the argument unchanged, because a surrogate half
 *    is General_Category Cs (Surrogate) and simply is not a member of
 *    any Unicode property this header's functions consult -- exactly
 *    like any other out-of-table wint_t, WEOF included, needs no
 *    special-casing to fall out the same way (see src/internal/libc.h's
 *    "Unicode Character Database" section for the one function,
 *    iswprint(), where that "absent means false" default has to be
 *    written explicitly rather than falling out for free).
 */

#ifndef _WCTYPE_H
#define _WCTYPE_H

#include <features.h>
#include <string_tokens.h>

#define __NEED_wint_t
#define __NEED_wctype_t

#include <bits/alltypes.h>

#ifdef __cplusplus
extern "C" {
#endif

#undef WEOF
#define WEOF 0xffffffffU

/* wctrans_t: "a scalar type ... values which represent locale-specific
 * character mappings" (wctype.h.html DESCRIPTION).  ntlibc's one locale
 * defines exactly two mappings ("tolower", "toupper" -- wctrans.html
 * "the following character mapping names are defined in all locales"),
 * so a small dense int enum is all the opacity this type needs; there
 * is no shared __NEED_wctrans_t machinery in bits/alltypes.h to hook
 * into (nothing else needs the type), so it is defined right here. */
typedef int wctrans_t;

/* Every iswXXX() here (src/ctype/isw*.c) either looks a real Unicode
 * property up directly (__unicode_is_*() in src/internal/unicode_data.c)
 * or, for iswalnum()/iswgraph()/iswpunct(), composes other iswXXX()
 * calls exactly the way ctype.h's isalnum()/ispunct() already compose
 * isalpha()/isdigit()/isgraph() -- see this header's own banner comment
 * for which property backs each one. towlower()/towupper()
 * (src/ctype/tow*.c) look up Unicode's own simple case mapping fields
 * the same way. None of this reads locale state beyond the fixed
 * C/POSIX-only design this whole header's own banner comment documents,
 * touches errno, or does I/O -- each is a total, deterministic function
 * of its argument(s), hence __pure__. */
int iswalnum(wint_t) __attribute__((__pure__));
int iswalpha(wint_t) __attribute__((__pure__));
int iswblank(wint_t) __attribute__((__pure__));
int iswcntrl(wint_t) __attribute__((__pure__));
int iswdigit(wint_t) __attribute__((__pure__));
int iswgraph(wint_t) __attribute__((__pure__));
int iswlower(wint_t) __attribute__((__pure__));
int iswprint(wint_t) __attribute__((__pure__));
int iswpunct(wint_t) __attribute__((__pure__));
int iswspace(wint_t) __attribute__((__pure__));
int iswupper(wint_t) __attribute__((__pure__));
int iswxdigit(wint_t) __attribute__((__pure__));

/* iswctype() (src/ctype/iswctype.c) is a closed switch over the twelve
 * iswXXX() functions above, keyed on the wctype_t desc; wctype()
 * (src/ctype/wctype.c) only strcmp()s name against a fixed static
 * array of the twelve class-name literals, reading its own arguments
 * and this tree's fixed constant table only -- no locale variation is
 * possible (this tree has exactly one locale), no errno, no writes. */
int iswctype(wint_t, wctype_t) __attribute__((__pure__));
wctype_t wctype(const char * withtok(null_terminated)) __attribute__((__pure__));

/* towctrans()/wctrans() (src/ctype/towctrans.c, wctrans.c) are the same
 * shape as iswctype()/wctype() just above: a closed switch/strcmp
 * dispatch to towlower()/towupper(), with no locale variation, errno,
 * or writes anywhere in either body. */
wint_t towlower(wint_t) __attribute__((__pure__));
wint_t towupper(wint_t) __attribute__((__pure__));
wint_t towctrans(wint_t, wctrans_t) __attribute__((__pure__));
wctrans_t wctrans(const char * withtok(null_terminated)) __attribute__((__pure__));

#ifdef __cplusplus
}
#endif

#endif

// NOLINTEND(bugprone-reserved-identifier,cert-dcl37-c,cert-dcl51-cpp)
