/* SPDX-FileCopyrightText: (C) 2026 Gavin John
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 * Signals, as far as they can be had.
 *
 * There is no asynchronous delivery from other processes: kill() can
 * only end a process, not interrupt it.  What does work is what a single
 * program generates itself -- raise(), abort(), a write to a broken
 * pipe, and hardware faults (SIGSEGV, SIGFPE, SIGILL, SIGBUS), which
 * arrive as NT exceptions and are turned into signals by a vectored
 * exception handler installed at startup.
 *
 * Ctrl-C and Ctrl-Break are a separate story: csrss delivers those
 * through kernel32's console control mechanism, not as NT exceptions,
 * and there is no ntdll path to it at all (see CONTRIBUTING.md).  With
 * NTLIBC_USE_KERNEL32, __signal_init() registers a handler with
 * SetConsoleCtrlHandler() that turns CTRL_C_EVENT/CTRL_BREAK_EVENT into
 * SIGINT via __raise_internal(), same as the vectored handler does for
 * DBG_CONTROL_C/DBG_CONTROL_BREAK.  Without it (the default build),
 * Ctrl-C is never turned into a signal; the default console behaviour,
 * which ends the process, stays in effect.
 */
#include <signal.h>
#include <unistd.h>
#include <stdlib.h>
#include <string.h>
#include <stdio.h>
#include <errno.h>
#include "libc.h"
#ifdef NTLIBC_USE_KERNEL32
#include "kernel32.h"
#endif

static void (*handlers[_NSIG])(int);
static sigset_t blocked;
static sigset_t pending;

/* Per-signal sa_mask/sa_flags, as installed by sigaction().  signal()
 * and sigset() leave these at their zero-initialized defaults (empty
 * mask, no flags), matching their simpler contract. */
static sigset_t act_mask[_NSIG];
static int act_flags[_NSIG];

static int sig_valid(int sig) { return sig > 0 && sig < _NSIG; }

/* Set only by exception_handler(), immediately around its call into
 * __raise_internal(), so a SIGSEGV/SIGBUS/SIGILL/SIGFPE handler
 * installed with SA_SIGINFO can be told this delivery came from a
 * hardware fault rather than kill()/raise() -- see the siginfo_t
 * construction in __raise_internal() below. No locking, same as every
 * other global here (this file's header comment: no threading support
 * to speak of, and delivery is synchronous). */
static int fault_active;
static void *fault_addr;
static int fault_si_code;   /* computed by exception_handler(), see there */

void (*signal(int sig, void (*h)(int)))(int)
{
	void (*old)(int);
	if (!sig_valid(sig) || sig == SIGKILL || sig == SIGSTOP) { errno = EINVAL; return SIG_ERR; }
	old = handlers[sig];
	handlers[sig] = h;
	return old;
}

int sigaction(int sig, const struct sigaction *act, struct sigaction *old)
{
	if (!sig_valid(sig) || sig == SIGKILL || sig == SIGSTOP) { errno = EINVAL; return -1; }
	if (old) {
		memset(old, 0, sizeof *old);
		old->sa_handler = handlers[sig];
		old->sa_mask = act_mask[sig];
		old->sa_flags = act_flags[sig];
	}
	if (act) {
		handlers[sig] = act->sa_handler;
		act_mask[sig] = act->sa_mask;
		/* SA_RESTART: meaningless here.  ntlibc never suspends a thread
		 * mid-syscall waiting on a signal in the first place -- there is
		 * no asynchronous delivery to interrupt anything with (see this
		 * file's header comment) -- so there is no EINTR-vs-restart
		 * choice for it to make.  Accepted and remembered (round-trips
		 * through sigaction(..., &old)) but otherwise a no-op.
		 *
		 * SA_ONSTACK: implemented. sigaltstack() below keeps the
		 * registered stack and sig_dispatch() switches to it around
		 * the handler call. Synchronous delivery is what makes that
		 * cheap: a kernel has to build a signal frame on the alternate
		 * stack and return through sigreturn, whereas this library owns
		 * the call site, so an alternate stack is a stack switch and
		 * nothing more (src/signal/$ARCH/altstack.S).
		 *
		 * SA_NOCLDSTOP/SA_NOCLDWAIT/SA_RESTORER: accepted and stored
		 * but not acted on -- SIGCHLD is never generated by this
		 * library at all (children are reaped synchronously through
		 * wait()/waitpid()), so the CLD flags have nothing to modify.
		 * SA_NODEFER, SA_RESETHAND and SA_SIGINFO are likewise
		 * meaningful under synchronous, in-process delivery and are
		 * genuinely implemented. */
		act_flags[sig] = act->sa_flags;
	}
	return 0;
}

static int default_action(int sig)
{
	switch (sig) {
	case SIGCHLD: case SIGURG: case SIGWINCH: case SIGCONT:
		return 0;   /* ignore */
	default:
		return 1;   /* terminate */
	}
}

/* Deliver a signal to this process now.  Returns 0 if it was handled or
 * ignored and control may continue; does not return if the default
 * action is to die. */
static stack_t alt_stack;   /* ss_sp == 0 means none is installed */
static int alt_active;      /* nonzero while a handler runs on it */

/* Defined in src/signal/$ARCH/altstack.S -- PE builds only.
 *
 * tools/asan-build.sh and tools/fuzz.sh compile the C sources under
 * src/ natively with clang and link no .S at all, so the symbol simply
 * does not exist there.
 * Nor could those files be reused if it did: the x86_64 one takes its
 * arguments in rcx/rdx/r8 per the Windows x64 ABI, which is not where a
 * SysV ELF caller puts them. */
#ifdef _WIN32
void __sig_call_on_altstack(void *sp, void (*fn)(void *), void *arg);
#endif

/* One shape for both handler signatures, so the stack switch below has a
 * single void(*)(void *) to call whichever kind of handler is installed. */
struct sig_delivery {
	void (*h)(int);
	void (*hsi)(int, siginfo_t *, void *);
	siginfo_t *si;
	int sig;
};

static void sig_deliver(void *p)
{
	struct sig_delivery *d = p;
	if (d->hsi) d->hsi(d->sig, d->si, NULL);
	else d->h(d->sig);
}

/* Run one delivery, on the alternate stack where the disposition asked
 * for it and one is installed.
 *
 * The !alt_active term is not belt-and-braces: a signal raised from
 * inside a handler that is already running on the alternate stack must
 * keep using the stack it is on, or the nested delivery would reset the
 * stack pointer to the top and write over its own caller's frames.
 * sigaltstack.html says the alternate stack is in use "until the handler
 * returns", and SS_ONSTACK is what a handler reads to detect this. */
static void sig_dispatch(struct sig_delivery *d, int flags)
{
#ifdef _WIN32
	if ((flags & SA_ONSTACK) && alt_stack.ss_sp && !alt_active) {
		void *top = (char *)alt_stack.ss_sp + alt_stack.ss_size;
		alt_active = 1;
		__sig_call_on_altstack(top, sig_deliver, d);
		alt_active = 0;
	} else {
		sig_deliver(d);
	}
#else
	/* Native (AddressSanitizer / libFuzzer) build: deliver on the
	 * current stack.
	 *
	 * Not merely because the asm above is absent. A raw stack switch is
	 * actively wrong under ASan, which tracks frames on the stack it
	 * knows about and offers __sanitizer_start_switch_fiber() precisely
	 * so a program that changes stacks can tell it; switching without
	 * that produces false reports about the stack it lost track of. The
	 * subject of this build is the memory safety of OS-independent code,
	 * not signal delivery.
	 *
	 * alt_active is deliberately NOT set here. Setting it would make
	 * sigaltstack() report SS_ONSTACK -- "a handler is running on the
	 * alternate stack" -- during a delivery that is doing no such thing,
	 * which is the exact lie this whole change removed. A native build
	 * reports honestly that it is not on the alternate stack; SA_ONSTACK
	 * is covered by `make check` under Wine and on real Windows, where
	 * the switch is real. */
	(void)flags;
	sig_deliver(d);
#endif
}

int __raise_internal(int sig)
{
	void (*h)(int);
	if (!sig_valid(sig)) { errno = EINVAL; return -1; }
	if (sigismember(&blocked, sig)) { sigaddset(&pending, sig); return 0; }
	h = handlers[sig];
	if (h == SIG_IGN) return 0;
	if (h == SIG_DFL) {
		if (!default_action(sig)) return 0;
		__stdio_exit();
		__nt_exit(__NT_SIGNAL_EXIT(sig));
	}
	/* else: h is a real handler.  Written as an else rather than a
	 * fallthrough because __nt_exit is _Noreturn (libc.h) but cppcheck
	 * does not track that, and so reads the fallthrough as h(sig) being
	 * reachable with h == SIG_DFL, which is NULL.
	 *
	 * BSD semantics: the disposition stays installed across delivery,
	 * unless the caller asked for SA_RESETHAND -- unlike plain System V,
	 * which would always restore SIG_DFL before calling the handler. */
	else {
		sigset_t saved = blocked;
		int flags = act_flags[sig];
		struct sig_delivery d;
		int i;

		/* Zeroed so sig_deliver() can tell the two handler shapes
		 * apart by which pointer is set; it lives on the ordinary
		 * stack and is read from the alternate one, which is fine --
		 * switching stacks does not unmap the old one. */
		memset(&d, 0, sizeof d);
		d.sig = sig;

		/* sigaction.html DESCRIPTION, SA_RESETHAND: "the disposition of
		 * the signal shall be reset to SIG_DFL ... on entry to the
		 * signal handler." Reset before calling h(), same as the real
		 * clause requires, and drop the recorded mask/flags with it --
		 * they belong to the sigaction() call that installed this
		 * handler, and a plain SIG_DFL has neither. */
		if (flags & SA_RESETHAND) {
			handlers[sig] = SIG_DFL;
			sigemptyset(&act_mask[sig]);
			act_flags[sig] = 0;
		}

		/* sigaction.html DESCRIPTION: "the signal being delivered ...
		 * shall be added to [the thread's signal mask] unless
		 * SA_NODEFER ... was specified", along with every signal in
		 * sa_mask, for the duration of the handler. This can only ever
		 * matter for a signal raised from *within* the handler -- see
		 * this file's header comment -- but that is exactly the case
		 * POSIX describes, since delivery here is always synchronous. */
		/* sigorset() would say this in one call, but its prototype is
		 * only visible under _BSD_SOURCE/_GNU_SOURCE (signal.h), which
		 * this file does not define -- so fold sa_mask in a signal at a
		 * time with sigaddset()/sigismember(), which are always
		 * declared. */
		for (i = 1; i < _NSIG; i++)
			if (sigismember(&act_mask[sig], i)) sigaddset(&blocked, i);
		if (!(flags & SA_NODEFER)) sigaddset(&blocked, sig);
		sigdelset(&blocked, SIGKILL);
		sigdelset(&blocked, SIGSTOP);

		/* sigaction.html DESCRIPTION: "If SA_SIGINFO is set ...
		 * sa_sigaction ... specif[ies] a signal-catching function" that
		 * takes (int, siginfo_t *, void *) instead of (int). sigaction()
		 * stores act->sa_handler into handlers[sig] (above), which reads
		 * the same bits as act->sa_sigaction -- both are members of the
		 * same union slot in struct sigaction (include/signal.h) -- so
		 * h already holds the right function pointer; it is only cast
		 * back to its real, three-argument type here. */
		if (flags & SA_SIGINFO) {
			void (*hsi)(int, siginfo_t *, void *) =
				(void (*)(int, siginfo_t *, void *))(void *)h;
			siginfo_t si;

			memset(&si, 0, sizeof si);
			si.si_signo = sig;
			si.si_errno = 0;
			if (fault_active) {
				/* signal.h.html siginfo_t DESCRIPTION: si_addr is
				 * defined for a hardware-fault signal
				 * (SIGILL/SIGFPE/SIGSEGV/SIGBUS); exception_handler()
				 * below sets fault_addr from the NT EXCEPTION_RECORD
				 * for the exception codes that actually carry a
				 * faulting address.
				 *
				 * si_code: exception_handler() below has already
				 * computed the real fault subcode into fault_si_code
				 * -- see the derivation there (a straight
				 * ExceptionCode -> FPE_.../ILL_.../BUS_... table for
				 * most cases, plus a NtQueryVirtualMemory() lookup to
				 * tell SEGV_MAPERR from SEGV_ACCERR). Just read it
				 * back. */
				si.si_code = fault_si_code;
				si.si_addr = fault_addr;
			} else {
				/* raise.html: raise() "shall be equivalent to calling
				 * kill(getpid(), sig)"; kill()'s self-delivery path
				 * (src/signal/signal.c's kill()) and the SIGPIPE/
				 * SIGINT deliveries elsewhere in this file all funnel
				 * through here the same way, none of them hardware
				 * faults, so SI_USER ("signal sent by kill()",
				 * signal.h.html) plus the sender's own pid/uid is
				 * correct for every one of them. */
				si.si_code = SI_USER;
				si.si_pid = getpid();
				si.si_uid = getuid();
			}
			d.hsi = hsi;
			d.si = &si;
			sig_dispatch(&d, flags);
		} else {
			d.h = h;
			sig_dispatch(&d, flags);
		}

		blocked = saved;
	}
	return 0;
}

int raise(int sig) { return __raise_internal(sig) < 0 ? -1 : 0; }

int kill(pid_t pid, int sig)
{
	struct __child *c;
	HANDLE h;
	NTSTATUS st;
	OBJECT_ATTRIBUTES oa;
	CLIENT_ID cid;

	/* kill.html DESCRIPTION: pid == 0 reaches "all processes ... whose
	 * process group ID is equal to the process group ID of the
	 * sender", and pid == -1 reaches "all processes ... for which the
	 * process has permission to send that signal" -- both defined in
	 * terms of a set of processes ntlibc has no way to enumerate (see
	 * src/unistd/ids.c: every process is its own group of one here, and
	 * this library tracks no process list beyond its own children).
	 * What both sets provably contain, on any POSIX system, is the
	 * caller itself: a process always has permission to signal itself,
	 * and is always a member of its own process group. Under the
	 * group-of-one model that is also *all* either set can ever
	 * contain, so "send to every process in {caller}" is not a
	 * degenerate stand-in for the real thing -- it is the real thing,
	 * fully enumerated. -1 is folded in here, alongside the existing
	 * 0 case, rather than falling into the general "pid < 0 -> process
	 * group, ESRCH" catch-all below. */
	if (pid == getpid() || pid == 0 || pid == -1) {
		if (!sig) return 0;
		return raise(sig);
	}
	if (pid < 0) { errno = ESRCH; return -1; }
	c = __child_find(pid);
	if (c) h = c->h;
	else {
		InitializeObjectAttributes(&oa, 0, 0, 0, 0);
		cid.UniqueProcess = (HANDLE)(ULONG_PTR)pid;
		cid.UniqueThread = 0;
		/* The access mask below decides which errno the caller sees,
		 * so it is load-bearing and not merely "enough rights for
		 * what we do next".  kill.html's "[EPERM] The process does
		 * not have permission to send the signal" is produced here
		 * by NT's own access check on the target process object --
		 * ntlibc performs no identity comparison of its own, and
		 * src/unistd/ids.c's single fixed uid has nothing to do with
		 * it.  Measured on real Windows 11 Pro 22621 against the
		 * System process (pid 4), from an ELEVATED token:
		 *
		 *   PROCESS_TERMINATE | QUERY_LIMITED_INFORMATION -> c0000022
		 *                                        (ACCESS_DENIED)
		 *   PROCESS_QUERY_LIMITED_INFORMATION alone       -> 00000000
		 *                                        (SUCCESS)
		 *   PROCESS_TERMINATE alone                       -> c0000022
		 *                                        (ACCESS_DENIED)
		 *
		 * The denial is specific to PROCESS_TERMINATE on a protected
		 * process, not a blanket refusal to touch pid 4.  Narrowing
		 * this mask to query-only would therefore turn a correct
		 * EPERM into a silent success, and would break
		 * test/posix-kill-perm-win.c for a reason that looks
		 * unrelated to the change.  Keep PROCESS_TERMINATE in the
		 * mask even if a future caller only needs to query.
		 *
		 * The ESRCH arm below is a genuinely different status, not a
		 * second reading of the same failure: a nonexistent pid
		 * answered STATUS_INVALID_CID (c000000b) in the same run. */
		st = NtOpenProcess(&h, PROCESS_TERMINATE | PROCESS_QUERY_LIMITED_INFORMATION, &oa, &cid);
		if (!NT_SUCCESS(st)) { errno = st == STATUS_ACCESS_DENIED ? EPERM : ESRCH; return -1; }
	}
	if (!sig) { if (!c) NtClose(h); return 0; }
	st = NtTerminateProcess(h, __NT_SIGNAL_EXIT(sig));
	if (!c) NtClose(h);
	if (!NT_SUCCESS(st) && st != STATUS_PROCESS_IS_TERMINATING) return __set_errno_status(st);
	return 0;
}

int killpg(pid_t pg, int sig) { return kill(pg, sig); }

int sigemptyset(sigset_t *s) { memset(s, 0, sizeof *s); return 0; }
int sigfillset(sigset_t *s) { memset(s, 0xff, sizeof *s); return 0; }
int sigaddset(sigset_t *s, int sig) { if (!sig_valid(sig)) { errno = EINVAL; return -1; } s->__bits[sig / (8 * sizeof(long))] |= 1UL << (sig % (8 * sizeof(long))); return 0; }
int sigdelset(sigset_t *s, int sig) { if (!sig_valid(sig)) { errno = EINVAL; return -1; } s->__bits[sig / (8 * sizeof(long))] &= ~(1UL << (sig % (8 * sizeof(long)))); return 0; }
int sigismember(const sigset_t *s, int sig) { if (!sig_valid(sig)) { errno = EINVAL; return -1; } return !!(s->__bits[sig / (8 * sizeof(long))] & (1UL << (sig % (8 * sizeof(long))))); }
int sigisemptyset(const sigset_t *s) { size_t i; for (i = 0; i < sizeof s->__bits / sizeof s->__bits[0]; i++) if (s->__bits[i]) return 0; return 1; }
int sigorset(sigset_t *d, const sigset_t *a, const sigset_t *b) { size_t i; for (i = 0; i < sizeof d->__bits / sizeof d->__bits[0]; i++) d->__bits[i] = a->__bits[i] | b->__bits[i]; return 0; }

int sigprocmask(int how, const sigset_t *set, sigset_t *old)
{
	int i;
	if (old) *old = blocked;
	if (set) {
		switch (how) {
		case SIG_BLOCK: sigorset(&blocked, &blocked, set); break;
		case SIG_UNBLOCK: for (i = 1; i < _NSIG; i++) if (sigismember(set, i)) sigdelset(&blocked, i); break;
		case SIG_SETMASK: blocked = *set; break;
		default: errno = EINVAL; return -1;
		}
		sigdelset(&blocked, SIGKILL);
		sigdelset(&blocked, SIGSTOP);
		/* deliver anything unblocked and pending */
		for (i = 1; i < _NSIG; i++)
			if (sigismember(&pending, i) && !sigismember(&blocked, i)) { sigdelset(&pending, i); __raise_internal(i); }
	}
	return 0;
}

int sigpending(sigset_t *s) { *s = pending; return 0; }
int sigsuspend(const sigset_t *s) { (void)s; errno = EINTR; return -1; }
int sigwait(const sigset_t *s, int *sig) { (void)s; (void)sig; errno = EINVAL; return EINVAL; }
int siginterrupt(int sig, int flag) { (void)sig; (void)flag; return 0; }
/* The alternate signal stack, and whether a handler is running on it.
 *
 * This used to be a stub that ignored ss, reported SS_DISABLE, and
 * returned 0 -- success for work it had not done. That is the worst
 * shape an unimplemented function can take: a caller that checks the
 * return value is told its stack was installed, and only finds out
 * otherwise by reading back a stack that is not there. 26 Open POSIX
 * sigaction cases died on exactly that, exiting 255 rather than failing
 * cleanly, which is why they read as ABNORMAL rather than FAIL.
 *
 * No locking, the same as every other piece of state in this file: there
 * are no threads to speak of and delivery is synchronous. */

int sigaltstack(const stack_t *ss, stack_t *old)
{
	/* sigaltstack.html: old is filled in before any change from ss is
	 * applied, so a caller may swap stacks in one call. */
	if (old) {
		old->ss_sp = alt_stack.ss_sp;
		old->ss_size = alt_stack.ss_size;
		old->ss_flags = alt_stack.ss_sp
			? (alt_active ? SS_ONSTACK : 0)
			: SS_DISABLE;
	}
	if (ss) {
		/* "[EPERM] An attempt was made to modify an active stack." */
		if (alt_active) { errno = EPERM; return -1; }
		/* "[EINVAL] The ss argument is not a null pointer, and the
		 * ss_flags member ... contains flags other than SS_DISABLE." */
		if (ss->ss_flags & ~(int)SS_DISABLE) { errno = EINVAL; return -1; }
		if (ss->ss_flags & SS_DISABLE) {
			alt_stack.ss_sp = 0;
			alt_stack.ss_size = 0;
			alt_stack.ss_flags = SS_DISABLE;
		} else {
			/* "[ENOMEM] The size of the alternate stack area is less
			 * than MINSIGSTKSZ." */
			if (ss->ss_size < MINSIGSTKSZ) { errno = ENOMEM; return -1; }
			if (!ss->ss_sp) { errno = EINVAL; return -1; }
			alt_stack.ss_sp = ss->ss_sp;
			alt_stack.ss_size = ss->ss_size;
			alt_stack.ss_flags = 0;
		}
	}
	return 0;
}

int __libc_current_sigrtmin(void) { return 35; }
int __libc_current_sigrtmax(void) { return _NSIG - 1; }
/* sigaddset() is the only place these two ever look at sig, so its
 * failure is the whole of sigset.html's "[EINVAL] The sig argument is an
 * illegal signal number" for them: dropping it does not degrade to a
 * failed sigprocmask(), because the set is then simply left empty and an
 * empty mask is a legal argument that sigprocmask() reports success for.
 * Returning here also leaves the process mask untouched, as a shall-fail
 * call must. */
int sighold(int sig) { sigset_t s; sigemptyset(&s); if (sigaddset(&s, sig) < 0) return -1; return sigprocmask(SIG_BLOCK, &s, 0); }
int sigrelse(int sig) { sigset_t s; sigemptyset(&s); if (sigaddset(&s, sig) < 0) return -1; return sigprocmask(SIG_UNBLOCK, &s, 0); }

/* sigset.html is not signal() with a different name, and the difference
 * is entirely about the signal mask.  RETURN VALUE: "Upon successful
 * completion, sigset() shall return SIG_HOLD if the signal had been
 * blocked and the signal's previous disposition if it had not been
 * blocked."  DESCRIPTION, for the ordinary disposition-setting case:
 * "sig shall be removed from the calling process' signal mask" -- the
 * SIG_HOLD return is how the caller learns that just happened, which is
 * why the two clauses have to be implemented together.  And for
 * func == SIG_HOLD: "sig shall be added to the calling process' signal
 * mask and its disposition shall remain unchanged" -- the one call that
 * moves the mask the other way and installs nothing.
 *
 * The unblock is done after the new disposition is in place, not before:
 * sigprocmask(SIG_UNBLOCK) delivers whatever became deliverable, and a
 * signal that arrived while sig was held belongs to the handler the
 * caller is installing now, not to the one it is replacing. */
void (*sigset(int sig, void (*h)(int)))(int)
{
	void (*old)(int);
	int was_blocked;
	sigset_t one;

	if (!sig_valid(sig) || sig == SIGKILL || sig == SIGSTOP) { errno = EINVAL; return SIG_ERR; }
	was_blocked = sigismember(&blocked, sig);
	sigemptyset(&one);
	sigaddset(&one, sig);

	if (h == SIG_HOLD) {
		old = handlers[sig];   /* read before the mask moves: sigprocmask()
		                        * runs whatever became deliverable, and a
		                        * handler may install a new disposition */
		if (sigprocmask(SIG_BLOCK, &one, 0) < 0) return SIG_ERR;
		return was_blocked ? SIG_HOLD : old;
	}

	old = signal(sig, h);
	if (old == SIG_ERR) return SIG_ERR;
	if (!was_blocked) return old;
	if (sigprocmask(SIG_UNBLOCK, &one, 0) < 0) return SIG_ERR;
	return SIG_HOLD;
}
int sigpause(int sig) { (void)sig; errno = EINTR; return -1; }

/* SEGV_MAPERR vs SEGV_ACCERR (signal.h.html siginfo_t DESCRIPTION) for
 * an EXCEPTION_ACCESS_VIOLATION/EXCEPTION_IN_PAGE_ERROR fault: NT's
 * EXCEPTION_RECORD only says whether the access was a read/write/
 * execute, not whether the page was unmapped or merely off-limits --
 * but NtQueryVirtualMemory(MemoryBasicInformation) on the faulting
 * address answers exactly that, through State (src/internal/nt.h):
 *
 *   MEM_FREE     nothing is mapped there at all         -> SEGV_MAPERR
 *   MEM_RESERVE  address space reserved, never committed
 *                (no backing page to access either)      -> SEGV_MAPERR
 *   MEM_COMMIT   a real page exists; the fault is
 *                Protect denying this exact access       -> SEGV_ACCERR
 *
 * NOT ATOMIC / TOCTOU: this call happens after the fault, not as part
 * of it -- nothing stops another thread from mapping, unmapping or
 * reprotecting the same address in between (VirtualAlloc/VirtualFree/
 * VirtualProtect-equivalent). For a synchronous fault handled on the
 * faulting thread with no other thread racing that address -- the
 * ordinary case, and the only one this library's own tests provoke --
 * the two states cannot practically diverge; it is not a guarantee
 * either POSIX or this library can make in the general, multithreaded
 * case. If the query itself fails (STATUS_ACCESS_DENIED touching a
 * kernel address, an already-torn-down process, etc.) SEGV_MAPERR is
 * the honest fallback: "cannot even ask" is closer to "not mapped"
 * than to "mapped but protected". */
static int segv_code(void *addr)
{
	MEMORY_BASIC_INFORMATION mbi;
	SIZE_T ret = 0;
	NTSTATUS st;

	memset(&mbi, 0, sizeof mbi);
	st = NtQueryVirtualMemory(NtCurrentProcess(), addr, MemoryBasicInformation, &mbi, sizeof mbi, &ret);
	if (!NT_SUCCESS(st)) return SEGV_MAPERR;
	return mbi.State == MEM_COMMIT ? SEGV_ACCERR : SEGV_MAPERR;
}

/* NT exceptions that correspond to synchronous signals, and (for the
 * fault-shaped ones) the si_code that names the fault precisely --
 * signal.h.html siginfo_t DESCRIPTION requires si_code to be one of
 * these fault-specific values, not left as a generic SI_KERNEL, for
 * SIGILL/SIGFPE/SIGSEGV/SIGBUS "generated by the implementation for
 * some reason not covered by [SI_USER etc.]". Most codes fall straight
 * out of ExceptionCode; only SEGV_MAPERR/SEGV_ACCERR need the extra
 * NtQueryVirtualMemory() lookup above. */
static LONG NTAPI exception_handler(EXCEPTION_POINTERS *ep)
{
	int sig, code;
	ULONG excode = ep->ExceptionRecord->ExceptionCode;

	switch (excode) {
	case EXCEPTION_ACCESS_VIOLATION:
	case EXCEPTION_IN_PAGE_ERROR:
		sig = SIGSEGV;
		code = segv_code((void *)ep->ExceptionRecord->ExceptionInformation[1]);
		break;
	case EXCEPTION_STACK_OVERFLOW:
		/* Running off the end of the reserved stack region: by
		 * definition there is no committed page to have been denied
		 * access to, so this is a mapping failure, not a protection
		 * one -- SEGV_MAPERR, without needing (or trusting) a query:
		 * EXCEPTION_STACK_OVERFLOW's EXCEPTION_RECORD does not
		 * reliably carry a faulting address the way access-violation
		 * does (ExceptionInformation[1] is meaningful only for
		 * EXCEPTION_ACCESS_VIOLATION/EXCEPTION_IN_PAGE_ERROR), and
		 * this exception is already unambiguous on its own. */
		sig = SIGSEGV;
		code = SEGV_MAPERR;
		break;
	case EXCEPTION_DATATYPE_MISALIGNMENT: sig = SIGBUS; code = BUS_ADRALN; break;
	case EXCEPTION_ILLEGAL_INSTRUCTION: sig = SIGILL; code = ILL_ILLOPC; break;
	case EXCEPTION_PRIV_INSTRUCTION: sig = SIGILL; code = ILL_PRVOPC; break;
	case EXCEPTION_INT_DIVIDE_BY_ZERO: sig = SIGFPE; code = FPE_INTDIV; break;
	case EXCEPTION_INT_OVERFLOW: sig = SIGFPE; code = FPE_INTOVF; break;
	case EXCEPTION_FLT_DIVIDE_BY_ZERO: sig = SIGFPE; code = FPE_FLTDIV; break;
	case EXCEPTION_FLT_INVALID_OPERATION: sig = SIGFPE; code = FPE_FLTINV; break;
	case EXCEPTION_FLT_OVERFLOW: sig = SIGFPE; code = FPE_FLTOVF; break;
	case EXCEPTION_FLT_UNDERFLOW: sig = SIGFPE; code = FPE_FLTUND; break;
	case EXCEPTION_FLT_INEXACT_RESULT: sig = SIGFPE; code = FPE_FLTRES; break;
	case EXCEPTION_FLT_DENORMAL_OPERAND:
		/* A real FP condition (an operand was a denormal), but POSIX's
		 * FPE_* list (signal.h.html) has no member for it -- INTDIV/
		 * INTOVF/FLTDIV/FLTOVF/FLTUND/FLTRES/FLTINV are the whole set,
		 * and none of them is "denormal operand". Rather than pick the
		 * closest-sounding one and misreport the cause, fall back to
		 * SI_KERNEL: honest ("not from kill()/raise()"), not a
		 * fabricated FPE_* subcode. */
		sig = SIGFPE;
		code = SI_KERNEL;
		break;
	case EXCEPTION_BREAKPOINT: sig = SIGTRAP; code = SI_KERNEL; break;
	case DBG_CONTROL_C:
	case DBG_CONTROL_BREAK: sig = SIGINT; code = SI_KERNEL; break;
	case STATUS_GUARD_PAGE_VIOLATION:
		/* A distinct exception from EXCEPTION_ACCESS_VIOLATION (0x80000001
		 * vs 0xC0000005), raised on touching a PAGE_GUARD page -- most
		 * commonly something outside ntlibc probing a thread stack's
		 * own guard region. This library never sets PAGE_GUARD itself
		 * (no PAGE_GUARD bit among src/internal/nt.h's PAGE_* constants),
		 * so there is no case here to fold into SIGSEGV; treated like
		 * any other exception this handler does not claim, by falling
		 * through to the next handler instead of guessing a signal. */
	default: return EXCEPTION_CONTINUE_SEARCH;
	}
	if (handlers[sig] == SIG_DFL) {
		__stdio_exit();
		__nt_exit(__NT_SIGNAL_EXIT(sig));
	}
	if (handlers[sig] == SIG_IGN) {
		/* Ignoring a fault would loop forever; POSIX says undefined. Die. */
		if (sig != SIGINT && sig != SIGTRAP) __nt_exit(__NT_SIGNAL_EXIT(sig));
		return EXCEPTION_CONTINUE_EXECUTION;
	}
	/* Tell __raise_internal() this delivery is not a kill()/raise() --
	 * see the siginfo_t construction there. si_addr (signal.h.html) is
	 * only meaningful for the access-violation-shaped exceptions, whose
	 * EXCEPTION_RECORD documents ExceptionInformation[1] as the
	 * faulting address (src/internal/nt.h); the others (misalignment,
	 * illegal instruction, arithmetic traps, breakpoints, Ctrl-C) carry
	 * no such address, so fault_addr stays NULL for them. */
	fault_active = 1;
	fault_addr = (excode == EXCEPTION_ACCESS_VIOLATION || excode == EXCEPTION_IN_PAGE_ERROR)
	           ? (void *)ep->ExceptionRecord->ExceptionInformation[1] : NULL;
	fault_si_code = code;
	__raise_internal(sig);
	fault_active = 0;
	/* A handler that returns from a fault re-executes the instruction,
	 * as on Unix; for SIGINT/SIGTRAP continuing is the right thing. */
	return EXCEPTION_CONTINUE_EXECUTION;
}

#ifdef NTLIBC_USE_KERNEL32
/* Runs on a thread kernel32 creates for the purpose, not on the main
 * thread -- so this can race a main thread that is, say, in the middle
 * of sigprocmask() touching the same `handlers`/`blocked`/`pending`
 * globals.  ntlibc has no locking anywhere else either (there is no
 * threading support to speak of), so this is no worse than the existing
 * exception_handler(), which has the same race against a genuine
 * hardware fault; it is just now reachable from a real extra thread
 * instead of only in theory. */
static BOOL NTAPI ctrl_handler(DWORD type)
{
	switch (type) {
	case CTRL_C_EVENT:
	case CTRL_BREAK_EVENT:
		/* Same signal for both, same as the vectored handler does
		 * for DBG_CONTROL_C/DBG_CONTROL_BREAK: this library has no
		 * SIGBREAK, and neither does POSIX. */
		if (handlers[SIGINT] == SIG_DFL) return FALSE;  /* let the default action run */
		__raise_internal(SIGINT);
		return TRUE;
	default:
		/* CTRL_CLOSE_EVENT/CTRL_LOGOFF_EVENT/CTRL_SHUTDOWN_EVENT:
		 * no POSIX signal maps cleanly onto any of these (they are
		 * closer to being told the terminal hung up while nobody's
		 * home), and the handler thread is on a short clock before
		 * kernel32 kills the process regardless.  Leave the default
		 * behaviour -- the process ends -- in effect. */
		return FALSE;
	}
}
#endif

#ifdef NTLIBC_USE_KERNEL32
/* kernel32 is reached with LdrLoadDll()/LdrGetProcedureAddress() -- both
 * ntdll exports -- rather than by linking against kernel32's import
 * library.  That keeps NTLIBC_USE_KERNEL32 a purely load-time decision:
 * a binary built with it still only *links* against ntdll, and only
 * pulls kernel32 into its address space if it actually runs on a build
 * where this was requested.  (It also means there's no kernel32.def-vs-
 * tcc's-search-path question to worry about at link time -- see
 * CONTRIBUTING.md for why kernel32 is meant to be the exception, not
 * a routine dependency.) */
static void install_ctrl_handler(void)
{
	UNICODE_STRING dllname;
	ANSI_STRING procname;
	PVOID kernel32, proc;

	RtlInitUnicodeString(&dllname, L"kernel32.dll");
	if (!NT_SUCCESS(LdrLoadDll(NULL, NULL, &dllname, &kernel32))) return;

	procname.Buffer = "SetConsoleCtrlHandler";
	/* A 21-byte string literal, not anything a caller supplies, so this
	 * narrowing to the ANSI_STRING's USHORT lengths cannot wrap.
	 * USHORT-safe: 21-byte string literal. */
	procname.Length = procname.MaximumLength = (USHORT)strlen(procname.Buffer);
	if (!NT_SUCCESS(LdrGetProcedureAddress(kernel32, &procname, 0, &proc))) return;

	((BOOL (NTAPI *)(PHANDLER_ROUTINE, BOOL))proc)(ctrl_handler, TRUE);
}
#endif

void __signal_init(void)
{
	RtlAddVectoredExceptionHandler(1, exception_handler);
#ifdef NTLIBC_USE_KERNEL32
	install_ctrl_handler();
#else
	/* No ntdll path to console control events exists (see
	 * CONTRIBUTING.md); nothing to install.  Ctrl-C keeps ending the
	 * process via the console's own default handling. */
#endif
}

/* psignal.html DESCRIPTION: "shall write a message to the standard
 * error stream... If the argument message is not a null pointer,
 * message ... followed by a colon character and a <space> character ...
 * If message is a null pointer or points to the null string, the error
 * message shall consist only of [the strsignal() text]." Needs nothing
 * this file does not already have: strsignal() (src/string/strsignal.c)
 * for the text, stdio for the write. */
void psignal(int sig, const char *s)
{
	if (s && *s) fprintf(stderr, "%s: %s\n", s, strsignal(sig));
	else fprintf(stderr, "%s\n", strsignal(sig));
}

/* psiginfo.html DESCRIPTION: same message shape as psignal(), driven
 * off a siginfo_t's si_signo instead of a bare signal number -- "as if
 * generated by strsignal()". RETURN VALUE: "no return value" for
 * either. */
void psiginfo(const siginfo_t *pinfo, const char *s)
{
	psignal(pinfo->si_signo, s);
}
