/* SPDX-FileCopyrightText: (C) 2026 Gavin John
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 * Signals, as far as they can be had.
 *
 * There is no asynchronous delivery from other processes: kill() can
 * only end a process, not interrupt it.  What does work is what a single
 * program generates itself -- raise(), abort(), a write to a broken
 * pipe, and hardware faults (SIGSEGV, SIGFPE, SIGILL, SIGBUS), which
 * arrive as NT exceptions and are turned into signals by a vectored
 * exception handler installed at startup.
 *
 * Ctrl-C and Ctrl-Break are a separate story: csrss delivers those
 * through kernel32's console control mechanism, not as NT exceptions,
 * and there is no ntdll path to it at all (see CONTRIBUTING.md).  With
 * NTLIBC_USE_KERNEL32, __signal_init() registers a handler with
 * SetConsoleCtrlHandler() that turns CTRL_C_EVENT/CTRL_BREAK_EVENT into
 * SIGINT via __raise_internal(), same as the vectored handler does for
 * DBG_CONTROL_C/DBG_CONTROL_BREAK.  Without it (the default build),
 * Ctrl-C is never turned into a signal; the default console behaviour,
 * which ends the process, stays in effect.
 */
#include <signal.h>
#include <unistd.h>
#include <stdlib.h>
#include <string.h>
#include <stdio.h>
#include <errno.h>
#include "libc.h"
#ifdef NTLIBC_USE_KERNEL32
#include "kernel32.h"
#endif

static void (*handlers[_NSIG])(int);
static sigset_t blocked;
static sigset_t pending;

/* Per-signal sa_mask/sa_flags, as installed by sigaction().  signal()/
 * bsd_signal()/sigset() leave these at their zero-initialized defaults
 * (empty mask, no flags), matching their simpler contract. */
static sigset_t act_mask[_NSIG];
static int act_flags[_NSIG];

static int sig_valid(int sig) { return sig > 0 && sig < _NSIG; }

/* Set only by exception_handler(), immediately around its call into
 * __raise_internal(), so a SIGSEGV/SIGBUS/SIGILL/SIGFPE handler
 * installed with SA_SIGINFO can be told this delivery came from a
 * hardware fault rather than kill()/raise() -- see the siginfo_t
 * construction in __raise_internal() below. No locking, same as every
 * other global here (this file's header comment: no threading support
 * to speak of, and delivery is synchronous). */
static int fault_active;
static void *fault_addr;
static int fault_si_code;   /* computed by exception_handler(), see there */

void (*signal(int sig, void (*h)(int)))(int)
{
	void (*old)(int);
	if (!sig_valid(sig) || sig == SIGKILL || sig == SIGSTOP) { errno = EINVAL; return SIG_ERR; }
	old = handlers[sig];
	handlers[sig] = h;
	return old;
}

void (*bsd_signal(int sig, void (*h)(int)))(int) { return signal(sig, h); }

int sigaction(int sig, const struct sigaction *act, struct sigaction *old)
{
	if (!sig_valid(sig) || sig == SIGKILL || sig == SIGSTOP) { errno = EINVAL; return -1; }
	if (old) {
		memset(old, 0, sizeof *old);
		old->sa_handler = handlers[sig];
		old->sa_mask = act_mask[sig];
		old->sa_flags = act_flags[sig];
	}
	if (act) {
		handlers[sig] = act->sa_handler;
		act_mask[sig] = act->sa_mask;
		/* SA_RESTART: meaningless here.  ntlibc never suspends a thread
		 * mid-syscall waiting on a signal in the first place -- there is
		 * no asynchronous delivery to interrupt anything with (see this
		 * file's header comment) -- so there is no EINTR-vs-restart
		 * choice for it to make.  Accepted and remembered (round-trips
		 * through sigaction(..., &old)) but otherwise a no-op.
		 *
		 * SA_ONSTACK/SA_SIGINFO/SA_NOCLDSTOP/SA_NOCLDWAIT/SA_RESTORER:
		 * likewise accepted and stored but not acted on -- there is no
		 * alternate signal stack, no siginfo delivery, and SIGCHLD is
		 * never generated by this library at all (children are reaped
		 * synchronously through wait()/waitpid()), so the CLD flags have
		 * nothing to modify. SA_NODEFER and SA_RESETHAND, below, are the
		 * two flags that are meaningful under synchronous, in-process
		 * delivery and are genuinely implemented. */
		act_flags[sig] = act->sa_flags;
	}
	return 0;
}

static int default_action(int sig)
{
	switch (sig) {
	case SIGCHLD: case SIGURG: case SIGWINCH: case SIGCONT:
		return 0;   /* ignore */
	default:
		return 1;   /* terminate */
	}
}

/* Deliver a signal to this process now.  Returns 0 if it was handled or
 * ignored and control may continue; does not return if the default
 * action is to die. */
int __raise_internal(int sig)
{
	void (*h)(int);
	if (!sig_valid(sig)) { errno = EINVAL; return -1; }
	if (sigismember(&blocked, sig)) { sigaddset(&pending, sig); return 0; }
	h = handlers[sig];
	if (h == SIG_IGN) return 0;
	if (h == SIG_DFL) {
		if (!default_action(sig)) return 0;
		__stdio_exit();
		__nt_exit(__NT_SIGNAL_EXIT(sig));
	}
	/* else: h is a real handler.  Written as an else rather than a
	 * fallthrough because __nt_exit is _Noreturn (libc.h) but cppcheck
	 * does not track that, and so reads the fallthrough as h(sig) being
	 * reachable with h == SIG_DFL, which is NULL.
	 *
	 * BSD semantics: the disposition stays installed across delivery,
	 * unless the caller asked for SA_RESETHAND -- unlike plain System V,
	 * which would always restore SIG_DFL before calling the handler. */
	else {
		sigset_t saved = blocked;
		int flags = act_flags[sig];
		int i;

		/* sigaction.html DESCRIPTION, SA_RESETHAND: "the disposition of
		 * the signal shall be reset to SIG_DFL ... on entry to the
		 * signal handler." Reset before calling h(), same as the real
		 * clause requires, and drop the recorded mask/flags with it --
		 * they belong to the sigaction() call that installed this
		 * handler, and a plain SIG_DFL has neither. */
		if (flags & SA_RESETHAND) {
			handlers[sig] = SIG_DFL;
			sigemptyset(&act_mask[sig]);
			act_flags[sig] = 0;
		}

		/* sigaction.html DESCRIPTION: "the signal being delivered ...
		 * shall be added to [the thread's signal mask] unless
		 * SA_NODEFER ... was specified", along with every signal in
		 * sa_mask, for the duration of the handler. This can only ever
		 * matter for a signal raised from *within* the handler -- see
		 * this file's header comment -- but that is exactly the case
		 * POSIX describes, since delivery here is always synchronous. */
		/* sigorset() would say this in one call, but its prototype is
		 * only visible under _BSD_SOURCE/_GNU_SOURCE (signal.h), which
		 * this file does not define -- so fold sa_mask in a signal at a
		 * time with sigaddset()/sigismember(), which are always
		 * declared. */
		for (i = 1; i < _NSIG; i++)
			if (sigismember(&act_mask[sig], i)) sigaddset(&blocked, i);
		if (!(flags & SA_NODEFER)) sigaddset(&blocked, sig);
		sigdelset(&blocked, SIGKILL);
		sigdelset(&blocked, SIGSTOP);

		/* sigaction.html DESCRIPTION: "If SA_SIGINFO is set ...
		 * sa_sigaction ... specif[ies] a signal-catching function" that
		 * takes (int, siginfo_t *, void *) instead of (int). sigaction()
		 * stores act->sa_handler into handlers[sig] (above), which reads
		 * the same bits as act->sa_sigaction -- both are members of the
		 * same union slot in struct sigaction (include/signal.h) -- so
		 * h already holds the right function pointer; it is only cast
		 * back to its real, three-argument type here. */
		if (flags & SA_SIGINFO) {
			void (*hsi)(int, siginfo_t *, void *) =
				(void (*)(int, siginfo_t *, void *))(void *)h;
			siginfo_t si;

			memset(&si, 0, sizeof si);
			si.si_signo = sig;
			si.si_errno = 0;
			if (fault_active) {
				/* signal.h.html siginfo_t DESCRIPTION: si_addr is
				 * defined for a hardware-fault signal
				 * (SIGILL/SIGFPE/SIGSEGV/SIGBUS); exception_handler()
				 * below sets fault_addr from the NT EXCEPTION_RECORD
				 * for the exception codes that actually carry a
				 * faulting address.
				 *
				 * si_code: exception_handler() below has already
				 * computed the real fault subcode into fault_si_code
				 * -- see the derivation there (a straight
				 * ExceptionCode -> FPE_.../ILL_.../BUS_... table for
				 * most cases, plus a NtQueryVirtualMemory() lookup to
				 * tell SEGV_MAPERR from SEGV_ACCERR). Just read it
				 * back. */
				si.si_code = fault_si_code;
				si.si_addr = fault_addr;
			} else {
				/* raise.html: raise() "shall be equivalent to calling
				 * kill(getpid(), sig)"; kill()'s self-delivery path
				 * (src/signal/signal.c's kill()) and the SIGPIPE/
				 * SIGINT deliveries elsewhere in this file all funnel
				 * through here the same way, none of them hardware
				 * faults, so SI_USER ("signal sent by kill()",
				 * signal.h.html) plus the sender's own pid/uid is
				 * correct for every one of them. */
				si.si_code = SI_USER;
				si.si_pid = getpid();
				si.si_uid = getuid();
			}
			hsi(sig, &si, NULL);
		} else {
			h(sig);
		}

		blocked = saved;
	}
	return 0;
}

int raise(int sig) { return __raise_internal(sig) < 0 ? -1 : 0; }

int kill(pid_t pid, int sig)
{
	struct __child *c;
	HANDLE h;
	NTSTATUS st;
	OBJECT_ATTRIBUTES oa;
	CLIENT_ID cid;

	/* kill.html DESCRIPTION: pid == 0 reaches "all processes ... whose
	 * process group ID is equal to the process group ID of the
	 * sender", and pid == -1 reaches "all processes ... for which the
	 * process has permission to send that signal" -- both defined in
	 * terms of a set of processes ntlibc has no way to enumerate (see
	 * src/unistd/ids.c: every process is its own group of one here, and
	 * this library tracks no process list beyond its own children).
	 * What both sets provably contain, on any POSIX system, is the
	 * caller itself: a process always has permission to signal itself,
	 * and is always a member of its own process group. Under the
	 * group-of-one model that is also *all* either set can ever
	 * contain, so "send to every process in {caller}" is not a
	 * degenerate stand-in for the real thing -- it is the real thing,
	 * fully enumerated. -1 is folded in here, alongside the existing
	 * 0 case, rather than falling into the general "pid < 0 -> process
	 * group, ESRCH" catch-all below. */
	if (pid == getpid() || pid == 0 || pid == -1) {
		if (!sig) return 0;
		return raise(sig);
	}
	if (pid < 0) { errno = ESRCH; return -1; }
	c = __child_find(pid);
	if (c) h = c->h;
	else {
		InitializeObjectAttributes(&oa, 0, 0, 0, 0);
		cid.UniqueProcess = (HANDLE)(ULONG_PTR)pid;
		cid.UniqueThread = 0;
		st = NtOpenProcess(&h, PROCESS_TERMINATE | PROCESS_QUERY_LIMITED_INFORMATION, &oa, &cid);
		if (!NT_SUCCESS(st)) { errno = st == STATUS_ACCESS_DENIED ? EPERM : ESRCH; return -1; }
	}
	if (!sig) { if (!c) NtClose(h); return 0; }
	st = NtTerminateProcess(h, __NT_SIGNAL_EXIT(sig));
	if (!c) NtClose(h);
	if (!NT_SUCCESS(st) && st != STATUS_PROCESS_IS_TERMINATING) return __set_errno_status(st);
	return 0;
}

int killpg(pid_t pg, int sig) { return kill(pg, sig); }

int sigemptyset(sigset_t *s) { memset(s, 0, sizeof *s); return 0; }
int sigfillset(sigset_t *s) { memset(s, 0xff, sizeof *s); return 0; }
int sigaddset(sigset_t *s, int sig) { if (!sig_valid(sig)) { errno = EINVAL; return -1; } s->__bits[sig / (8 * sizeof(long))] |= 1UL << (sig % (8 * sizeof(long))); return 0; }
int sigdelset(sigset_t *s, int sig) { if (!sig_valid(sig)) { errno = EINVAL; return -1; } s->__bits[sig / (8 * sizeof(long))] &= ~(1UL << (sig % (8 * sizeof(long)))); return 0; }
int sigismember(const sigset_t *s, int sig) { if (!sig_valid(sig)) { errno = EINVAL; return -1; } return !!(s->__bits[sig / (8 * sizeof(long))] & (1UL << (sig % (8 * sizeof(long))))); }
int sigisemptyset(const sigset_t *s) { size_t i; for (i = 0; i < sizeof s->__bits / sizeof s->__bits[0]; i++) if (s->__bits[i]) return 0; return 1; }
int sigorset(sigset_t *d, const sigset_t *a, const sigset_t *b) { size_t i; for (i = 0; i < sizeof d->__bits / sizeof d->__bits[0]; i++) d->__bits[i] = a->__bits[i] | b->__bits[i]; return 0; }
int sigandset(sigset_t *d, const sigset_t *a, const sigset_t *b) { size_t i; for (i = 0; i < sizeof d->__bits / sizeof d->__bits[0]; i++) d->__bits[i] = a->__bits[i] & b->__bits[i]; return 0; }

int sigprocmask(int how, const sigset_t *set, sigset_t *old)
{
	int i;
	if (old) *old = blocked;
	if (set) {
		switch (how) {
		case SIG_BLOCK: sigorset(&blocked, &blocked, set); break;
		case SIG_UNBLOCK: for (i = 1; i < _NSIG; i++) if (sigismember(set, i)) sigdelset(&blocked, i); break;
		case SIG_SETMASK: blocked = *set; break;
		default: errno = EINVAL; return -1;
		}
		sigdelset(&blocked, SIGKILL);
		sigdelset(&blocked, SIGSTOP);
		/* deliver anything unblocked and pending */
		for (i = 1; i < _NSIG; i++)
			if (sigismember(&pending, i) && !sigismember(&blocked, i)) { sigdelset(&pending, i); __raise_internal(i); }
	}
	return 0;
}

int sigpending(sigset_t *s) { *s = pending; return 0; }
int sigsuspend(const sigset_t *s) { (void)s; errno = EINTR; return -1; }
int sigwait(const sigset_t *s, int *sig) { (void)s; (void)sig; errno = EINVAL; return EINVAL; }
int siginterrupt(int sig, int flag) { (void)sig; (void)flag; return 0; }
int sigaltstack(const stack_t *ss, stack_t *old) { (void)ss; if (old) { old->ss_sp = 0; old->ss_size = 0; old->ss_flags = SS_DISABLE; } return 0; }
int __libc_current_sigrtmin(void) { return 35; }
int __libc_current_sigrtmax(void) { return _NSIG - 1; }
int sighold(int sig) { sigset_t s; sigemptyset(&s); sigaddset(&s, sig); return sigprocmask(SIG_BLOCK, &s, 0); }
int sigrelse(int sig) { sigset_t s; sigemptyset(&s); sigaddset(&s, sig); return sigprocmask(SIG_UNBLOCK, &s, 0); }
void (*sigset(int sig, void (*h)(int)))(int) { return signal(sig, h); }
int sigpause(int sig) { (void)sig; errno = EINTR; return -1; }

/* SEGV_MAPERR vs SEGV_ACCERR (signal.h.html siginfo_t DESCRIPTION) for
 * an EXCEPTION_ACCESS_VIOLATION/EXCEPTION_IN_PAGE_ERROR fault: NT's
 * EXCEPTION_RECORD only says whether the access was a read/write/
 * execute, not whether the page was unmapped or merely off-limits --
 * but NtQueryVirtualMemory(MemoryBasicInformation) on the faulting
 * address answers exactly that, through State (src/internal/nt.h):
 *
 *   MEM_FREE     nothing is mapped there at all         -> SEGV_MAPERR
 *   MEM_RESERVE  address space reserved, never committed
 *                (no backing page to access either)      -> SEGV_MAPERR
 *   MEM_COMMIT   a real page exists; the fault is
 *                Protect denying this exact access       -> SEGV_ACCERR
 *
 * NOT ATOMIC / TOCTOU: this call happens after the fault, not as part
 * of it -- nothing stops another thread from mapping, unmapping or
 * reprotecting the same address in between (VirtualAlloc/VirtualFree/
 * VirtualProtect-equivalent). For a synchronous fault handled on the
 * faulting thread with no other thread racing that address -- the
 * ordinary case, and the only one this library's own tests provoke --
 * the two states cannot practically diverge; it is not a guarantee
 * either POSIX or this library can make in the general, multithreaded
 * case. If the query itself fails (STATUS_ACCESS_DENIED touching a
 * kernel address, an already-torn-down process, etc.) SEGV_MAPERR is
 * the honest fallback: "cannot even ask" is closer to "not mapped"
 * than to "mapped but protected". */
static int segv_code(void *addr)
{
	MEMORY_BASIC_INFORMATION mbi;
	SIZE_T ret = 0;
	NTSTATUS st;

	memset(&mbi, 0, sizeof mbi);
	st = NtQueryVirtualMemory(NtCurrentProcess(), addr, MemoryBasicInformation, &mbi, sizeof mbi, &ret);
	if (!NT_SUCCESS(st)) return SEGV_MAPERR;
	return mbi.State == MEM_COMMIT ? SEGV_ACCERR : SEGV_MAPERR;
}

/* NT exceptions that correspond to synchronous signals, and (for the
 * fault-shaped ones) the si_code that names the fault precisely --
 * signal.h.html siginfo_t DESCRIPTION requires si_code to be one of
 * these fault-specific values, not left as a generic SI_KERNEL, for
 * SIGILL/SIGFPE/SIGSEGV/SIGBUS "generated by the implementation for
 * some reason not covered by [SI_USER etc.]". Most codes fall straight
 * out of ExceptionCode; only SEGV_MAPERR/SEGV_ACCERR need the extra
 * NtQueryVirtualMemory() lookup above. */
static LONG NTAPI exception_handler(EXCEPTION_POINTERS *ep)
{
	int sig, code;
	ULONG excode = ep->ExceptionRecord->ExceptionCode;

	switch (excode) {
	case EXCEPTION_ACCESS_VIOLATION:
	case EXCEPTION_IN_PAGE_ERROR:
		sig = SIGSEGV;
		code = segv_code((void *)ep->ExceptionRecord->ExceptionInformation[1]);
		break;
	case EXCEPTION_STACK_OVERFLOW:
		/* Running off the end of the reserved stack region: by
		 * definition there is no committed page to have been denied
		 * access to, so this is a mapping failure, not a protection
		 * one -- SEGV_MAPERR, without needing (or trusting) a query:
		 * EXCEPTION_STACK_OVERFLOW's EXCEPTION_RECORD does not
		 * reliably carry a faulting address the way access-violation
		 * does (ExceptionInformation[1] is meaningful only for
		 * EXCEPTION_ACCESS_VIOLATION/EXCEPTION_IN_PAGE_ERROR), and
		 * this exception is already unambiguous on its own. */
		sig = SIGSEGV;
		code = SEGV_MAPERR;
		break;
	case EXCEPTION_DATATYPE_MISALIGNMENT: sig = SIGBUS; code = BUS_ADRALN; break;
	case EXCEPTION_ILLEGAL_INSTRUCTION: sig = SIGILL; code = ILL_ILLOPC; break;
	case EXCEPTION_PRIV_INSTRUCTION: sig = SIGILL; code = ILL_PRVOPC; break;
	case EXCEPTION_INT_DIVIDE_BY_ZERO: sig = SIGFPE; code = FPE_INTDIV; break;
	case EXCEPTION_INT_OVERFLOW: sig = SIGFPE; code = FPE_INTOVF; break;
	case EXCEPTION_FLT_DIVIDE_BY_ZERO: sig = SIGFPE; code = FPE_FLTDIV; break;
	case EXCEPTION_FLT_INVALID_OPERATION: sig = SIGFPE; code = FPE_FLTINV; break;
	case EXCEPTION_FLT_OVERFLOW: sig = SIGFPE; code = FPE_FLTOVF; break;
	case EXCEPTION_FLT_UNDERFLOW: sig = SIGFPE; code = FPE_FLTUND; break;
	case EXCEPTION_FLT_INEXACT_RESULT: sig = SIGFPE; code = FPE_FLTRES; break;
	case EXCEPTION_FLT_DENORMAL_OPERAND:
		/* A real FP condition (an operand was a denormal), but POSIX's
		 * FPE_* list (signal.h.html) has no member for it -- INTDIV/
		 * INTOVF/FLTDIV/FLTOVF/FLTUND/FLTRES/FLTINV are the whole set,
		 * and none of them is "denormal operand". Rather than pick the
		 * closest-sounding one and misreport the cause, fall back to
		 * SI_KERNEL: honest ("not from kill()/raise()"), not a
		 * fabricated FPE_* subcode. */
		sig = SIGFPE;
		code = SI_KERNEL;
		break;
	case EXCEPTION_BREAKPOINT: sig = SIGTRAP; code = SI_KERNEL; break;
	case DBG_CONTROL_C:
	case DBG_CONTROL_BREAK: sig = SIGINT; code = SI_KERNEL; break;
	case STATUS_GUARD_PAGE_VIOLATION:
		/* A distinct exception from EXCEPTION_ACCESS_VIOLATION (0x80000001
		 * vs 0xC0000005), raised on touching a PAGE_GUARD page -- most
		 * commonly something outside ntlibc probing a thread stack's
		 * own guard region. This library never sets PAGE_GUARD itself
		 * (no PAGE_GUARD bit among src/internal/nt.h's PAGE_* constants),
		 * so there is no case here to fold into SIGSEGV; treated like
		 * any other exception this handler does not claim, by falling
		 * through to the next handler instead of guessing a signal. */
	default: return EXCEPTION_CONTINUE_SEARCH;
	}
	if (handlers[sig] == SIG_DFL) {
		__stdio_exit();
		__nt_exit(__NT_SIGNAL_EXIT(sig));
	}
	if (handlers[sig] == SIG_IGN) {
		/* Ignoring a fault would loop forever; POSIX says undefined. Die. */
		if (sig != SIGINT && sig != SIGTRAP) __nt_exit(__NT_SIGNAL_EXIT(sig));
		return EXCEPTION_CONTINUE_EXECUTION;
	}
	/* Tell __raise_internal() this delivery is not a kill()/raise() --
	 * see the siginfo_t construction there. si_addr (signal.h.html) is
	 * only meaningful for the access-violation-shaped exceptions, whose
	 * EXCEPTION_RECORD documents ExceptionInformation[1] as the
	 * faulting address (src/internal/nt.h); the others (misalignment,
	 * illegal instruction, arithmetic traps, breakpoints, Ctrl-C) carry
	 * no such address, so fault_addr stays NULL for them. */
	fault_active = 1;
	fault_addr = (excode == EXCEPTION_ACCESS_VIOLATION || excode == EXCEPTION_IN_PAGE_ERROR)
	           ? (void *)ep->ExceptionRecord->ExceptionInformation[1] : NULL;
	fault_si_code = code;
	__raise_internal(sig);
	fault_active = 0;
	/* A handler that returns from a fault re-executes the instruction,
	 * as on Unix; for SIGINT/SIGTRAP continuing is the right thing. */
	return EXCEPTION_CONTINUE_EXECUTION;
}

#ifdef NTLIBC_USE_KERNEL32
/* Runs on a thread kernel32 creates for the purpose, not on the main
 * thread -- so this can race a main thread that is, say, in the middle
 * of sigprocmask() touching the same `handlers`/`blocked`/`pending`
 * globals.  ntlibc has no locking anywhere else either (there is no
 * threading support to speak of), so this is no worse than the existing
 * exception_handler(), which has the same race against a genuine
 * hardware fault; it is just now reachable from a real extra thread
 * instead of only in theory. */
static BOOL NTAPI ctrl_handler(DWORD type)
{
	switch (type) {
	case CTRL_C_EVENT:
	case CTRL_BREAK_EVENT:
		/* Same signal for both, same as the vectored handler does
		 * for DBG_CONTROL_C/DBG_CONTROL_BREAK: this library has no
		 * SIGBREAK, and neither does POSIX. */
		if (handlers[SIGINT] == SIG_DFL) return FALSE;  /* let the default action run */
		__raise_internal(SIGINT);
		return TRUE;
	default:
		/* CTRL_CLOSE_EVENT/CTRL_LOGOFF_EVENT/CTRL_SHUTDOWN_EVENT:
		 * no POSIX signal maps cleanly onto any of these (they are
		 * closer to being told the terminal hung up while nobody's
		 * home), and the handler thread is on a short clock before
		 * kernel32 kills the process regardless.  Leave the default
		 * behaviour -- the process ends -- in effect. */
		return FALSE;
	}
}
#endif

#ifdef NTLIBC_USE_KERNEL32
/* kernel32 is reached with LdrLoadDll()/LdrGetProcedureAddress() -- both
 * ntdll exports -- rather than by linking against kernel32's import
 * library.  That keeps NTLIBC_USE_KERNEL32 a purely load-time decision:
 * a binary built with it still only *links* against ntdll, and only
 * pulls kernel32 into its address space if it actually runs on a build
 * where this was requested.  (It also means there's no kernel32.def-vs-
 * tcc's-search-path question to worry about at link time -- see
 * CONTRIBUTING.md for why kernel32 is meant to be the exception, not
 * a routine dependency.) */
static void install_ctrl_handler(void)
{
	UNICODE_STRING dllname;
	ANSI_STRING procname;
	PVOID kernel32, proc;

	RtlInitUnicodeString(&dllname, L"kernel32.dll");
	if (!NT_SUCCESS(LdrLoadDll(NULL, NULL, &dllname, &kernel32))) return;

	procname.Buffer = "SetConsoleCtrlHandler";
	/* A 21-byte string literal, not anything a caller supplies, so this
	 * narrowing to the ANSI_STRING's USHORT lengths cannot wrap.
	 * USHORT-safe: 21-byte string literal. */
	procname.Length = procname.MaximumLength = (USHORT)strlen(procname.Buffer);
	if (!NT_SUCCESS(LdrGetProcedureAddress(kernel32, &procname, 0, &proc))) return;

	((BOOL (NTAPI *)(PHANDLER_ROUTINE, BOOL))proc)(ctrl_handler, TRUE);
}
#endif

void __signal_init(void)
{
	RtlAddVectoredExceptionHandler(1, exception_handler);
#ifdef NTLIBC_USE_KERNEL32
	install_ctrl_handler();
#else
	/* No ntdll path to console control events exists (see
	 * CONTRIBUTING.md); nothing to install.  Ctrl-C keeps ending the
	 * process via the console's own default handling. */
#endif
}

/* psignal.html DESCRIPTION: "shall write a message to the standard
 * error stream... If the argument message is not a null pointer,
 * message ... followed by a colon character and a <space> character ...
 * If message is a null pointer or points to the null string, the error
 * message shall consist only of [the strsignal() text]." Needs nothing
 * this file does not already have: strsignal() (src/string/strsignal.c)
 * for the text, stdio for the write. */
void psignal(int sig, const char *s)
{
	if (s && *s) fprintf(stderr, "%s: %s\n", s, strsignal(sig));
	else fprintf(stderr, "%s\n", strsignal(sig));
}

/* psiginfo.html DESCRIPTION: same message shape as psignal(), driven
 * off a siginfo_t's si_signo instead of a bare signal number -- "as if
 * generated by strsignal()". RETURN VALUE: "no return value" for
 * either. */
void psiginfo(const siginfo_t *pinfo, const char *s)
{
	psignal(pinfo->si_signo, s);
}
